### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/bugzilla-graphql-gateway#3]
Is this repo currently hosted somewhere? [Codetribute](https://github.com/mozilla-frontend-infra/codetribute) uses it. If it's not, I can send a pull-request with the `Procfile` and create a repo for it on Heroku.

**Comment by eliperelman** [comment]
Ship it to Heroku works for me. We should probably make a PR so this uses a Bugzilla API key to avoid rate limiting in Heroku.
