### ISSUE TITLE
Query bug's comments

### ISSUE THREAD

**Issue by fiennyangeln** [mozilla-frontend-infra/bugzilla-graphql-gateway#6]
@helfi92 @eliperelman Can we add a way to get bug's first comment? In the bugzilla REST API, bug's comment is located on a different endpoint from the bug, for bug it is `/rest/bug/(bug_id)`, for comment `/rest/bug/(bug_id)/comment`.

And how are we going to do it? Will it be a separate query / a field in the bug/bugs query?

**Comment by helfi92** [comment]
Yes, this would require adding a query for comments in the gateway. I'll try and send a PR for this on Monday so that you can use it.

**Comment by eliperelman** [comment]
This is done now, right?

**Comment by helfi92** [comment]
Indeed.
